services:
  - type: web
    name: ping-pong-multiplayer
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true 